title: Hyunseong Kim
description: 
# site_title: '@abhn - Abhishek Nagekar'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: hyunsk1995
# blog_url: https://www.nagekar.com
email: hyunskcj@gmail.com
# keybase_username: abhn
# twitter_username: abhn_
# reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 